[project]
name = "v2x-intersection-safety"
version = "0.1.0"
description = "Add your description here"
requires-python = ">=3.13"
dependencies = [
    "fastapi>=0.134.0",
    "pip>=26.0.1",
    "pydantic>=2.12.5",
    "uvicorn[standard]>=0.41.0",
    "websockets>=16.0",
]
